// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TimeUnityPortal.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("IntegrationReqDataDriven", Description="\tIntegration Login POST request\r\n\tRead Data From Excel\r\n\tIntegration Send Order R" +
        "equest", SourceFile="Features\\IntegrationReqDataDriven.feature", SourceLine=0)]
    public partial class IntegrationReqDataDrivenFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "IntegrationReqDataDriven.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "IntegrationReqDataDriven", "\tIntegration Login POST request\r\n\tRead Data From Excel\r\n\tIntegration Send Order R" +
                    "equest", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("POST Integration Login Request, Verify, Store generated Token", SourceLine=6)]
        [TechTalk.SpecRun.IgnoreAttribute()]
        public virtual void POSTIntegrationLoginRequestVerifyStoreGeneratedToken()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("POST Integration Login Request, Verify, Store generated Token", null, new string[] {
                        "ignore"});
#line 7
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 8
 testRunner.Given("I make call to integration login POST request", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 9
 testRunner.Then("I verify login response is valid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 10
 testRunner.And("I store token from response", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 11
 testRunner.And("Create and write Login request and response data to excel file", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        public virtual void POSTIntegrationSendOrderRequestWithGeneratedTokenFromLoginRequestAndReadingRequestBodyDataFromExcelVerifyStoreGeneratedDealURN(string cellStart, string cellEnd, string sheetNumber, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "ignore"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("POST Integration Send Order Request with generated Token from Login Request and R" +
                    "eading Request Body Data from excel, Verify, Store generated DealURN", null, @__tags);
#line 13
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 15
 testRunner.Given(string.Format("I read Send Order request data {0}, {1} & {2} from excel", cellStart, cellEnd, sheetNumber), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 16
 testRunner.Then("I make call to integration send order POST request with data from excel", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 17
 testRunner.Then("I verify send order response is valid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 18
 testRunner.And("I store dealURN from response", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 19
 testRunner.And("Create and write Send Order request and response data to excel file", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("POST Integration Send Order Request with generated Token from Login Request and R" +
            "eading Request Body Data from excel, Verify, Store generated DealURN, C4", SourceLine=22)]
        [TechTalk.SpecRun.IgnoreAttribute()]
        public virtual void POSTIntegrationSendOrderRequestWithGeneratedTokenFromLoginRequestAndReadingRequestBodyDataFromExcelVerifyStoreGeneratedDealURN_C4()
        {
#line 13
this.POSTIntegrationSendOrderRequestWithGeneratedTokenFromLoginRequestAndReadingRequestBodyDataFromExcelVerifyStoreGeneratedDealURN("C4", "BJ4", "1", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("POST Integration Send Order Request with generated Token from Login Request and R" +
            "eading Request Body Data from excel, Verify, Store generated DealURN, C5", SourceLine=22)]
        [TechTalk.SpecRun.IgnoreAttribute()]
        public virtual void POSTIntegrationSendOrderRequestWithGeneratedTokenFromLoginRequestAndReadingRequestBodyDataFromExcelVerifyStoreGeneratedDealURN_C5()
        {
#line 13
this.POSTIntegrationSendOrderRequestWithGeneratedTokenFromLoginRequestAndReadingRequestBodyDataFromExcelVerifyStoreGeneratedDealURN("C5", "BJ5", "1", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("POST Integration Send Order Request with generated Token from Login Request and R" +
            "eading Request Body Data from excel, Verify, Store generated DealURN, C6", SourceLine=22)]
        [TechTalk.SpecRun.IgnoreAttribute()]
        public virtual void POSTIntegrationSendOrderRequestWithGeneratedTokenFromLoginRequestAndReadingRequestBodyDataFromExcelVerifyStoreGeneratedDealURN_C6()
        {
#line 13
this.POSTIntegrationSendOrderRequestWithGeneratedTokenFromLoginRequestAndReadingRequestBodyDataFromExcelVerifyStoreGeneratedDealURN("C6", "BJ6", "1", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("POST Integration Send Order Request with generated Token from Login Request and R" +
            "eading Request Body Data from excel, Verify, Store generated DealURN, C7", SourceLine=22)]
        [TechTalk.SpecRun.IgnoreAttribute()]
        public virtual void POSTIntegrationSendOrderRequestWithGeneratedTokenFromLoginRequestAndReadingRequestBodyDataFromExcelVerifyStoreGeneratedDealURN_C7()
        {
#line 13
this.POSTIntegrationSendOrderRequestWithGeneratedTokenFromLoginRequestAndReadingRequestBodyDataFromExcelVerifyStoreGeneratedDealURN("C7", "BJ7", "1", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("POST Integration Send Order Request with generated Token from Login Request and R" +
            "eading Request Body Data from excel, Verify, Store generated DealURN, C8", SourceLine=22)]
        [TechTalk.SpecRun.IgnoreAttribute()]
        public virtual void POSTIntegrationSendOrderRequestWithGeneratedTokenFromLoginRequestAndReadingRequestBodyDataFromExcelVerifyStoreGeneratedDealURN_C8()
        {
#line 13
this.POSTIntegrationSendOrderRequestWithGeneratedTokenFromLoginRequestAndReadingRequestBodyDataFromExcelVerifyStoreGeneratedDealURN("C8", "BJ8", "1", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("POST Integration Send Order Request with generated Token from Login Request and R" +
            "eading Request Body Data from excel, Verify, Store generated DealURN, C9", SourceLine=22)]
        [TechTalk.SpecRun.IgnoreAttribute()]
        public virtual void POSTIntegrationSendOrderRequestWithGeneratedTokenFromLoginRequestAndReadingRequestBodyDataFromExcelVerifyStoreGeneratedDealURN_C9()
        {
#line 13
this.POSTIntegrationSendOrderRequestWithGeneratedTokenFromLoginRequestAndReadingRequestBodyDataFromExcelVerifyStoreGeneratedDealURN("C9", "BJ9", "1", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("POST Integration Send Order Request with generated Token from Login Request and R" +
            "eading Request Body Data from excel, Verify, Store generated DealURN, C10", SourceLine=22)]
        [TechTalk.SpecRun.IgnoreAttribute()]
        public virtual void POSTIntegrationSendOrderRequestWithGeneratedTokenFromLoginRequestAndReadingRequestBodyDataFromExcelVerifyStoreGeneratedDealURN_C10()
        {
#line 13
this.POSTIntegrationSendOrderRequestWithGeneratedTokenFromLoginRequestAndReadingRequestBodyDataFromExcelVerifyStoreGeneratedDealURN("C10", "BJ10", "1", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("POST Integration Send Order Request with generated Token from Login Request and R" +
            "eading Request Body Data from excel, Verify, Store generated DealURN, C11", SourceLine=22)]
        [TechTalk.SpecRun.IgnoreAttribute()]
        public virtual void POSTIntegrationSendOrderRequestWithGeneratedTokenFromLoginRequestAndReadingRequestBodyDataFromExcelVerifyStoreGeneratedDealURN_C11()
        {
#line 13
this.POSTIntegrationSendOrderRequestWithGeneratedTokenFromLoginRequestAndReadingRequestBodyDataFromExcelVerifyStoreGeneratedDealURN("C11", "BJ11", "1", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("POST Integration Send Order Request with generated Token from Login Request and R" +
            "eading Request Body Data from excel, Verify, Store generated DealURN, C12", SourceLine=22)]
        [TechTalk.SpecRun.IgnoreAttribute()]
        public virtual void POSTIntegrationSendOrderRequestWithGeneratedTokenFromLoginRequestAndReadingRequestBodyDataFromExcelVerifyStoreGeneratedDealURN_C12()
        {
#line 13
this.POSTIntegrationSendOrderRequestWithGeneratedTokenFromLoginRequestAndReadingRequestBodyDataFromExcelVerifyStoreGeneratedDealURN("C12", "BJ12", "1", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("POST Integration Send Order Request with generated Token from Login Request and R" +
            "eading Request Body Data from excel, Verify, Store generated DealURN, C13", SourceLine=22)]
        [TechTalk.SpecRun.IgnoreAttribute()]
        public virtual void POSTIntegrationSendOrderRequestWithGeneratedTokenFromLoginRequestAndReadingRequestBodyDataFromExcelVerifyStoreGeneratedDealURN_C13()
        {
#line 13
this.POSTIntegrationSendOrderRequestWithGeneratedTokenFromLoginRequestAndReadingRequestBodyDataFromExcelVerifyStoreGeneratedDealURN("C13", "BJ13", "1", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("POST Integration Send Order Request with generated Token from Login Request and R" +
            "eading Request Body Data from excel, Verify, Store generated DealURN, C14", SourceLine=22)]
        [TechTalk.SpecRun.IgnoreAttribute()]
        public virtual void POSTIntegrationSendOrderRequestWithGeneratedTokenFromLoginRequestAndReadingRequestBodyDataFromExcelVerifyStoreGeneratedDealURN_C14()
        {
#line 13
this.POSTIntegrationSendOrderRequestWithGeneratedTokenFromLoginRequestAndReadingRequestBodyDataFromExcelVerifyStoreGeneratedDealURN("C14", "BJ14", "1", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("POST Integration Send Order Request with generated Token from Login Request and R" +
            "eading Request Body Data from excel, Verify, Store generated DealURN, C15", SourceLine=22)]
        [TechTalk.SpecRun.IgnoreAttribute()]
        public virtual void POSTIntegrationSendOrderRequestWithGeneratedTokenFromLoginRequestAndReadingRequestBodyDataFromExcelVerifyStoreGeneratedDealURN_C15()
        {
#line 13
this.POSTIntegrationSendOrderRequestWithGeneratedTokenFromLoginRequestAndReadingRequestBodyDataFromExcelVerifyStoreGeneratedDealURN("C15", "BJ15", "1", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("POST Integration Send Order Request with generated Token from Login Request and R" +
            "eading Request Body Data from excel, Verify, Store generated DealURN, C16", SourceLine=22)]
        [TechTalk.SpecRun.IgnoreAttribute()]
        public virtual void POSTIntegrationSendOrderRequestWithGeneratedTokenFromLoginRequestAndReadingRequestBodyDataFromExcelVerifyStoreGeneratedDealURN_C16()
        {
#line 13
this.POSTIntegrationSendOrderRequestWithGeneratedTokenFromLoginRequestAndReadingRequestBodyDataFromExcelVerifyStoreGeneratedDealURN("C16", "BJ16", "1", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("POST Integration Send Order Request with generated Token from Login Request and R" +
            "eading Request Body Data from excel, Verify, Store generated DealURN, C17", SourceLine=22)]
        [TechTalk.SpecRun.IgnoreAttribute()]
        public virtual void POSTIntegrationSendOrderRequestWithGeneratedTokenFromLoginRequestAndReadingRequestBodyDataFromExcelVerifyStoreGeneratedDealURN_C17()
        {
#line 13
this.POSTIntegrationSendOrderRequestWithGeneratedTokenFromLoginRequestAndReadingRequestBodyDataFromExcelVerifyStoreGeneratedDealURN("C17", "BJ17", "1", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("POST Integration Send Order Request with generated Token from Login Request and R" +
            "eading Request Body Data from excel, Verify, Store generated DealURN, C18", SourceLine=22)]
        [TechTalk.SpecRun.IgnoreAttribute()]
        public virtual void POSTIntegrationSendOrderRequestWithGeneratedTokenFromLoginRequestAndReadingRequestBodyDataFromExcelVerifyStoreGeneratedDealURN_C18()
        {
#line 13
this.POSTIntegrationSendOrderRequestWithGeneratedTokenFromLoginRequestAndReadingRequestBodyDataFromExcelVerifyStoreGeneratedDealURN("C18", "BJ18", "1", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("POST Integration Send Order Request with generated Token from Login Request and R" +
            "eading Request Body Data from excel, Verify, Store generated DealURN, C19", SourceLine=22)]
        [TechTalk.SpecRun.IgnoreAttribute()]
        public virtual void POSTIntegrationSendOrderRequestWithGeneratedTokenFromLoginRequestAndReadingRequestBodyDataFromExcelVerifyStoreGeneratedDealURN_C19()
        {
#line 13
this.POSTIntegrationSendOrderRequestWithGeneratedTokenFromLoginRequestAndReadingRequestBodyDataFromExcelVerifyStoreGeneratedDealURN("C19", "BJ19", "1", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("POST Integration Send Order Request with generated Token from Login Request and R" +
            "eading Request Body Data from excel, Verify, Store generated DealURN, C20", SourceLine=22)]
        [TechTalk.SpecRun.IgnoreAttribute()]
        public virtual void POSTIntegrationSendOrderRequestWithGeneratedTokenFromLoginRequestAndReadingRequestBodyDataFromExcelVerifyStoreGeneratedDealURN_C20()
        {
#line 13
this.POSTIntegrationSendOrderRequestWithGeneratedTokenFromLoginRequestAndReadingRequestBodyDataFromExcelVerifyStoreGeneratedDealURN("C20", "BJ20", "1", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("POST Integration Send Order Request with generated Token from Login Request and R" +
            "eading Request Body Data from excel, Verify, Store generated DealURN, C21", SourceLine=22)]
        [TechTalk.SpecRun.IgnoreAttribute()]
        public virtual void POSTIntegrationSendOrderRequestWithGeneratedTokenFromLoginRequestAndReadingRequestBodyDataFromExcelVerifyStoreGeneratedDealURN_C21()
        {
#line 13
this.POSTIntegrationSendOrderRequestWithGeneratedTokenFromLoginRequestAndReadingRequestBodyDataFromExcelVerifyStoreGeneratedDealURN("C21", "BJ21", "1", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("POST Integration Send Order Request with generated Token from Login Request and R" +
            "eading Request Body Data from excel, Verify, Store generated DealURN, C22", SourceLine=22)]
        [TechTalk.SpecRun.IgnoreAttribute()]
        public virtual void POSTIntegrationSendOrderRequestWithGeneratedTokenFromLoginRequestAndReadingRequestBodyDataFromExcelVerifyStoreGeneratedDealURN_C22()
        {
#line 13
this.POSTIntegrationSendOrderRequestWithGeneratedTokenFromLoginRequestAndReadingRequestBodyDataFromExcelVerifyStoreGeneratedDealURN("C22", "BJ22", "1", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("POST Integration Send Order Request with generated Token from Login Request and R" +
            "eading Request Body Data from excel, Verify, Store generated DealURN, C23", SourceLine=22)]
        [TechTalk.SpecRun.IgnoreAttribute()]
        public virtual void POSTIntegrationSendOrderRequestWithGeneratedTokenFromLoginRequestAndReadingRequestBodyDataFromExcelVerifyStoreGeneratedDealURN_C23()
        {
#line 13
this.POSTIntegrationSendOrderRequestWithGeneratedTokenFromLoginRequestAndReadingRequestBodyDataFromExcelVerifyStoreGeneratedDealURN("C23", "BJ23", "1", ((string[])(null)));
#line hidden
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
